name: find_freelancer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <=4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  expandable_page_view: ^1.0.17
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  photo_view: ^0.14.0
  show_up_animation: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/profile.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
